##---------------------------
# File 유형별 설정
##----------------------------
file:
  image:
    path:
      root: /app/image
  excel:
    path:
      root:

##---------------------------
# Spring 설정
##----------------------------
spring:
  # DB설정 ( 로컬과 동일 )

  # spring session 설정 ( 저장소를 redis로 )
  session:
    store-type: redis # @EnableRedisHttpSession를 활성화하여 SpringSessionRepositoryFilter에 등록
    redis:
      namespace: basketballDiary:session
  # redis 설정
  data:
    # docker-container간 통신을 위해서 container이름을 host명으로 반영
    # cf. docker container 실행시 두 container가 같은 network로 지정돼 있어야 함.
    redis:
      host: basketballDiary-redis-dev
      port: 6379
      password: basketball2022-dev

##---------------------------
# Spring-APIDocs 설정
##----------------------------
# local 상속

##---------------------------
# MyBatis 설정
##----------------------------
# local 상속

##---------------------------
# Server 설정
##----------------------------
server:
  port: 18080
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        name: basketballDiary-DEV230826
        same-site: lax
        secure: false
        http-only: true
        path: /

##---------------------------
# Logging 설정
##----------------------------
# local 상속

