## File 업로드 경로 설정
file:
  image:
    path:
      root: C://image
      ## 팀 프로필
      team-profile : /team/profile
      ## 팀 로고
      team-logo    : /team/logo
  excel:
    path:
      root:



spring:
  datasource:
    ## log4jdbc를 위한 url 및 driver-class-name 변경 (2022.02.26)
    ## url: jdbc:log4jdbc:mysql://basketdiary.cefnc9yxtv6y.ap-northeast-2.rds.amazonaws.com/basketdiary
    url: jdbc:log4jdbc:mysql://changkeeroom.iptime.org:53306/basketdiary
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: basketdiary
    password: basket5199

  # spring session 설정 ( 저장소를 redis로 )
  session:
    store-type: redis # @EnableRedisHttpSession를 활성화하여 SpringSessionRepositoryFilter에 등록
    redis:
      namespace: basketDairyApp:session
  # redis 설정
  data:
    redis:
      host: changkeeroom.iptime.org
      port: 16379
      password: basketball2022-local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

  ## HttpRequest Multipart 설정
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    # 참고자료 : https://jaehun2841.github.io/2018/12/30/2018-12-30-mybatis-returnInstanceForEmptyRow/#%EB%93%A4%EC%96%B4%EA%B0%80%EB%A9%B0
    # 참고자료 : https://oingdaddy.tistory.com/379
    # select 조회시 record가 없다면 null을 반환하는것이 기본설정(false), record가 없어도 instance를 반환하려면 true (instance를 반환한다는 것은 객체가 생성되는 것이고, 해당되는 데이터가 없기 때문에 객체의 모든 필드는 null값을 가지게 됨)
    return-instance-for-empty-row : false
  mapper-locations:
    - classpath:mvc/repository/**/*.xml

server:
  port: 18080
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        name: basketballD
        # sameSite 설정을 위한 속성값 - sameSite의 기본값은 lax로 제한적으로만 cookie가 세팅됨.
        # sameSite = none으로 하고, secure속성값을 추가해야함!
        # 참고 : https://yousrain.tistory.com/23, https://velog.io/@kwakwoohyun/%EC%9D%B4%EC%8A%88%EC%B2%98%EB%A6%AC-spring-boot-local-cookie
# 23.07.20 개발서버는 WS에서 백엔드 API를 호출함.
#           따라서 웹브라우저에서 개발서버를 호출하는 경우 origin이 다른 경우는 존재하지 않음.
#           이를 처리하기 위한 same-site와 secure 속성을 주석처리 ( 기본값 same-site=Lax 반영 )
        same-site: none   # 22.10.25 인준 : SameSite오류 해결 - 개념정리 필요
        secure: true      # 22.10.25 인준 : SameSite오류 해결 - 개념정리 필요
        http-only: true
        path: /

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

springdoc:
  swagger-ui:
    # swagger-ui 접근 경로
    path: /swagger-custom-ui.html