spring:
  datasource:
    ## log4jdbc를 위한 url 및 driver-class-name 변경 (2022.02.26)
    ## url: jdbc:mysql://basketball-diary.comugfwcpzzw.ap-northeast-2.rds.amazonaws.com/basketballDiaryTest
    url: jdbc:log4jdbc:mysql://basketball-diary.comugfwcpzzw.ap-northeast-2.rds.amazonaws.com/basketballDiaryTest
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: admin
    password: Basket5199

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    # 참고자료 : https://jaehun2841.github.io/2018/12/30/2018-12-30-mybatis-returnInstanceForEmptyRow/#%EB%93%A4%EC%96%B4%EA%B0%80%EB%A9%B0
    # 참고자료 : https://oingdaddy.tistory.com/379
    # select 조회시 record가 없다면 null을 반환하는것이 기본설정(false), record가 없어도 instance를 반환하려면 true (instance를 반환한다는 것은 객체가 생성되는 것이고, 해당되는 데이터가 없기 때문에 객체의 모든 필드는 null값을 가지게 됨)
    return-instance-for-empty-row : false
  mapper-locations:
    - classpath:mvc/repository/**/*.xml

server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        name: basketballDiary
#        domain: 127.0.0.1:5500 # sameSite 설정을 위한 속성값 - sameSite의 기본값은 lax로 제한적으로만 cookie가 세팅됨. sameSite = none으로 하고 https통신으로 바꿔줘야 함!
# 참고 : https://yousrain.tistory.com/23, https://velog.io/@kwakwoohyun/%EC%9D%B4%EC%8A%88%EC%B2%98%EB%A6%AC-spring-boot-local-cookie
        http-only: true
        path: /

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace