##---------------------------
# File 유형별 설정
##----------------------------
file:
  image:
    path:
      root: /app/image
  excel:
    path:
      root:

##---------------------------
# Spring 설정
##----------------------------
spring:
  # DB설정
  datasource:
    ## log4jdbc를 위한 url 및 driver-class-name 변경 (2022.02.26)
    url: jdbc:log4jdbc:mysql://23ggs.mooo.com:33306/basketballDiary-prd
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: APP-USER
    password: basketball-2021-prd

  # spring session 설정 ( 저장소를 redis로 )
  session:
    store-type: redis # @EnableRedisHttpSession를 활성화하여 SpringSessionRepositoryFilter에 등록
    redis:
      namespace: basketDairyApp:session
  # redis 설정
  data:
    # docker-container간 통신을 위해서 container이름을 host명으로 반영
    # cf. docker container 실행시 두 container가 같은 network로 지정돼 있어야 함.
    redis:
      host: basketball-redis-prd
      port: 6379
      password: basketball2022-redis-prd2024

##---------------------------
# Spring-APIDocs 설정
##----------------------------
spring-doc:
  swagger-ui:
    # swagger-ui 접근 경로 ( 운영환경은 별도의 접근제어 요망 )
    path:

##---------------------------
# MyBatis 설정
##----------------------------
# local 상속

##---------------------------
# Server 설정
##----------------------------
server:
  port: 38080
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
      cookie:
        name: basketballDiary-PRD
        same-site: lax
        secure: false
        http-only: true
        path: /


##---------------------------
# Logging 설정
##----------------------------
# local 상속



