### API001 : 소속팀 운영진 조회


### APIauthUserService : 소속팀 농구게임 목록조회
## 쿼리스트링 : 
## gameBgngYmd={gameBgngYmd}
## gameEndYmd={gameEndYmd}
## sidoCode={sidoCode}
## gamePlaceName={gamePlaceName}
## gameTypeCode={gameTypeCode}
## homeAwayCode={homeAwayCode} - 미구현.. 테이블 조인 필요

GET http://127.0.0.1:8080/api/myTeams/7/games
# Content-Type : application/json

## return값
# [
#     {
#         "gameSeq" : Long,
#         "gameYmd" : String,
#         "gamePlaceAddress" : String,
#         "gamePlaceName" : Srting,
#         "gameTypeCode" :  String,
#         "gameTypeCodeName" : String,
#         "gameJoinTeams" : [
#             {
#                 "gameJoinTeamSeq" : Long,
#                 "teamSeq" : Long,
#                 "teamName" : String,
#                 "homeAwayCode" : String,
#                 "homeAwayCodeName" : String,
#                 "quarters" : [
#                     {
#                         "quarterTeamRecordsSeq" : Long,
#                         "quarterCode" : String,
#                         "quarterCodeName" : String,
#                         "quarterScore" : Integer,
#                     },
#                     ...
#                 ]
#             },
#             ...
#         ]
#     },
#     ....
# ]

    
### API036 : 소속팀 전체 팀원 검색

### APIauthUserService : 소속팀 농구게임 목록조회
## 쿼리스트링 : 
##      pageNo={pageNo}
##      playerName={plyaerName}

GET http://127.0.0.1:8080/api/myTeams/7/allTeamMembers?playerName=성ㅈ
Cookie: basketballDiary=5B0257C060FCFFA13827DBC70BD03B12; Path=/; Secure; HttpOnly; SameSite=None
