### API001 : 소속팀 운영진 조회


### API052 : 소속팀 농구게임 목록조회
## 쿼리스트링 : 
## gameBgngYmd={gameBgngYmd}
## gameEndYmd={gameEndYmd}
## sidoCode={sidoCode}
## gamePlaceName={gamePlaceName}
## gameTypeCode={gameTypeCode}
## homeAwayCode={homeAwayCode}

GET http://127.0.0.1:8080/api/myTeams/{teamSeq}/games

## return값
[
    {
        "gameSeq" : Long,
        "gameYmd" : String,
        "gamePlaceAddress" : String,
        "gamePlaceName" : Srting,
        "gameTypeCode" :  String,
        "gameTypeCodeName" : String,
        "gameJoinTeams" : [
            {
                "gameJoinTeamSeq" : Long,
                "teamSeq" : Long,
                "teamName" : String,
                "homeAwayCode" : String,
                "homeAwayCodeName" : String,
                "quarters" : [
                    {
                        "quarterTeamRecordsSeq" : Long,
                        "quarterCode" : String,
                        "quarterCodeName" : String,
                        "quarterScore" : Integer,
                    },
                    ...
                ]
            },
            ...
        ]
    },
    ....
]
    

