### API019 : 팀 목록 조회
GET http://changkeeroom.iptime.org:8080/api/teams
Content-Type : application/json

### API021 : 팀 생성
POST http://127.0.0.1:8080/api/teams
Content-Type : application/json
Cookie: basketballDiary=A54591900B64027CBE3A71CC86CBDDEB

{

}


